/**
 * @author Saki
 * @date 2019-04-19 18:38:17
 * @Last Modified by: Saki
 * @Last Modified time: 2019-05-17 13:29:07
 *
 * Application index file – the app execution starts here
 * auto-generated by create-react-app script
 */

// core-js polyfills are required for IE11 compatibility. If you don't use IE then delete them
import "core-js/stable";

import React from 'react';
import ReactDOM from 'react-dom';

import App from './App.js';

ReactDOM.render(<App />, document.getElementById('container'));

// eof
